DEFINES += VERSION_MAJOR=0
DEFINES += VERSION_MINOR=1
DEFINES += VERSION_UPDATE=0
DEFINES += VERSION_BUILD=17

os2 {
    DEFINES += VERSION=\'\"v$${VERSION_MAJOR}.$${VERSION_MINOR}.$${VERSION_UPDATE}.$${VERSION_BUILD}\"\'
} else {
    DEFINES += VERSION=\\\"v$${VERSION_MAJOR}.$${VERSION_MINOR}.$${VERSION_UPDATE}.$${VERSION_BUILD}\\\"
}

