######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 25 12:46:47 2012
######################################################################

CONFIG += qtestlib
QT += network
TEMPLATE = app

include (../../src/http/http.pri)
# Input
HEADERS += mainwindow.h

SOURCES += main.cpp \
           mainwindow.cpp

FORMS += \
    mainwindow.ui

RESOURCES += ../../src/Icons/emule/emule.qrc
