######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 25 12:46:47 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . model unit
INCLUDEPATH += . unit

include (model/model.pri)
# Input
HEADERS += unit/share_files_test.h

SOURCES += main.cpp \
           unit/share_files_test.cpp
