######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 25 12:46:47 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . model unit
INCLUDEPATH += . unit model

# Input
HEADERS += mainwindow.h \
           model/qfileinfogatherer.h \
           model/qfilesystemsharemodel.h \
           model/shared_files_tree.h \
           unit/shared_tree_test.h
FORMS += mainwindow.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           model/qfileinfogatherer.cpp \
           model/qfilesystemsharemodel.cpp \
           model/shared_files_tree.cpp \
           unit/shared_tree_test.cpp
